version: '3'

services:
    postgresql:
        image: postgres:16.2-alpine3.19
        container_name: postgresql
        restart: always
        ports:
            - "5432:5432"
        networks:
            - my_network
        env_file:
            - ./websockets/.env
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - "80:80"
        depends_on:
            - api
            - websockets
        container_name: reverse_proxy
        networks:
            - my_network
    api:
        container_name: api
        build:
            context: ./api
            dockerfile: Dockerfile
        networks:
            - my_network
        depends_on:
            - postgresql
    websockets:
        container_name: websockets
        build:
            context: ./websockets
            dockerfile: Dockerfile
        networks:
            - my_network
        depends_on:
            - api
        env_file:
            - ./websockets/.env
        networks:
            - my_network
networks:
  my_network:
    driver: bridge

