# Generated by Django 5.0.4 on 2024-04-29 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(max_length=2048)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=2000)),
                ('avatar_url', models.CharField(blank=True, default='https://localhost/assets/images/anonimous.jpeg', max_length=2000)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('is_online', models.BooleanField(default=False)),
                ('is_playing', models.BooleanField(default=False)),
                ('points_earned', models.IntegerField(db_index=True, default=0)),
                ('number_of_followers', models.IntegerField(default=0)),
                ('number_of_following', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oauth2_platform', models.CharField(blank=True, max_length=100)),
                ('two_factor_auth', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=2000)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Followership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relevancy_score', models.IntegerField(db_index=True, default=0)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.user')),
            ],
        ),
    ]
