# Generated by Django 3.2.6 on 2024-04-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_users_user_friends_+', to='users.User'),
        ),
    ]
