# Generated by Django 5.0.4 on 2024-04-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(blank=True, default='https://localhost/assets/images/anonimous.jpeg', max_length=2000),
        ),
    ]
