# Generated by Django 4.2.10 on 2024-04-05 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demi_final_first_game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demi_final_first_game', to='games.game')),
                ('demi_final_second_game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demi_final_second_game', to='games.game')),
                ('final_game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_game', to='games.game')),
                ('fourth_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fourth_place', to='users.user')),
                ('second_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second_place', to='users.user')),
                ('third_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='third_place', to='users.user')),
                ('tournament_hoster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_hoster', to='users.user')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winner', to='users.user')),
            ],
        ),
    ]
