# Generated by Django 4.2.10 on 2024-04-18 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_tournament_id'),
        ('tournaments', '0004_alter_tournament_tournament_hoster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='demi_final_first_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demi_final_first_game', to='games.game'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='demi_final_second_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demi_final_second_game', to='games.game'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='final_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='final_game', to='games.game'),
        ),
    ]
