# Generated by Django 5.0.4 on 2024-04-22 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_score1_game_score2_alter_game_tournament_id'),
        ('tournaments', '0005_alter_tournament_demi_final_first_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='demi_final_first_game',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='demi_final_second_game',
        ),
        migrations.AddField(
            model_name='tournament',
            name='semi_final_first_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semi_final_first_game', to='games.game'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='semi_final_second_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semi_final_second_game', to='games.game'),
        ),
    ]
