# Generated by Django 4.2.10 on 2024-04-05 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=100)),
                ('is_vs_ai', models.BooleanField(default=False)),
                ('is_2x2', models.BooleanField(default=False)),
                ('state', models.CharField(max_length=100)),
                ('is_team1_won', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game_hoster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_hoster', to='users.user')),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player1', to='users.user')),
                ('player_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player2', to='users.user')),
                ('player_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player3', to='users.user')),
                ('player_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player4', to='users.user')),
            ],
        ),
    ]
