# Generated by Django 4.2.10 on 2024-04-05 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('games', '0002_game_is_part_of_tournament_alter_game_player_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_hoster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_hoster', to='users.user'),
        ),
    ]
