# Generated by Django 4.2.10 on 2024-04-18 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_tournament_tournament_hoster'),
        ('games', '0003_alter_game_game_hoster'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tournament_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tournaments.tournament'),
        ),
    ]
